### GetAll for Admin
GET http://localhost:3000/api/v1/clients
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsInNlc3Npb25JZCI6OSwiaWF0IjoxNzU3MDM1MjgwLCJleHAiOjE3NTcxMjE2ODB9.OvwM9FCn92AoyY4ZZlmEuvPAjN5xEW0xjtMpzLGlE20

### GetOne
GET http://localhost:3000/api/v1/users/3
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsInNlc3Npb25JZCI6OSwiaWF0IjoxNzU3MDM1MjgwLCJleHAiOjE3NTcxMjE2ODB9.OvwM9FCn92AoyY4ZZlmEuvPAjN5xEW0xjtMpzLGlE20

### currentUser
GET  http://localhost:3000/api/v1/users/currentUser
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsInNlc3Npb25JZCI6OSwiaWF0IjoxNzU3MDM1MjgwLCJleHAiOjE3NTcxMjE2ODB9.OvwM9FCn92AoyY4ZZlmEuvPAjN5xEW0xjtMpzLGlE20




### Update User
PATCH  http://localhost:3000/api/v1/users/3
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJhZG1pbiIsInNlc3Npb25JZCI6OSwiaWF0IjoxNzU3MDM1MjgwLCJleHAiOjE3NTcxMjE2ODB9.OvwM9FCn92AoyY4ZZlmEuvPAjN5xEW0xjtMpzLGlE20

{
  "username":"Hady 90 90"
}


### Delete User
DELETE   http://localhost:3000/api/v1/users/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsInVzZXJUeXBlIjoiYWRtaW4iLCJpYXQiOjE3NTU5MTk4MDQsImV4cCI6MTc1NTkyMzQwNH0.IWAIroaVkFQ8FN8QS3xZYwnVeIzFoT7NTV2Med18zxM



