import { DataSource } from 'typeorm';
import { User } from '../Modules/users/entities/user.entity';
import { Client } from '../Modules/users/clients/entities/client.entity';
import { Vendor } from '../Modules/vendor/entities/vendor.entity';
import { Project } from '../Modules/projects/entities/project.entity';
import { UserType } from '../utils/types';
export async function seedDatabase(dataSource: DataSource) {
  const userRepository = dataSource.getRepository(User);
  const clientRepository = dataSource.getRepository(Client);
  const vendorRepository = dataSource.getRepository(Vendor);
  const projectRepository = dataSource.getRepository(Project);
  // Seed Users
  await userRepository.save([
    {
      id: 1,
      username: 'admin',
      email: 'admin@example.com',
      password: '$2a$10$DlQAXr5qbbA6rLA1QUay4.YhDSu1ewNrApMizDn6ILSzG3iouqsXy',     // admin123
      userType: UserType.ADMIN,
      isAccountVerified: true,
      emailVerificationToken: null,
      resetPasswordToken: null,
      resetPasswordTokenExpiresAt: null,
    },
    {
      id: 2,
      username: 'Client ONE',
      email: 'Client_ONE@gmail.com',
      password: '$2a$10$uJGkMhKgSgv4XN73CaqhD.mGtfXUbeTwO1mRFqUAq60XuUBMrZ4ZG',           // 123456789
      userType: UserType.CLIENT,
      isAccountVerified: true,
      emailVerificationToken: null,
      resetPasswordToken: null,
      resetPasswordTokenExpiresAt: null,
    },
    {
      id: 3,
      username: 'Client TWO',
      email: 'Client_TWO@gmail.com',
      password: '$2a$10$uJGkMhKgSgv4XN73CaqhD.mGtfXUbeTwO1mRFqUAq60XuUBMrZ4ZG',           // 123456789
      userType: UserType.CLIENT,
      isAccountVerified: true,
      emailVerificationToken: null,
      resetPasswordToken: null,
      resetPasswordTokenExpiresAt: null,
    },
  ]);
  // Seed Clients
  await clientRepository.save([
    {
      id: 1,
      company_name: 'Client ONE Corp',
      contact_email: 'Client_ONE@gmail.com',
      userId: 2,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'), 
    },
    {
      id: 2,
      company_name: 'Client TWO Corp',
      contact_email: 'Client_TWO@gmail.com',
      userId: 3,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'), 
    },
  ]);
  
  // Seed Vendors
  await vendorRepository.save([
    {
      id: 1,
      name: 'NVIDIA',
      email: 'NVIDIA@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'USA', 'GER'],
      services_offered: ['Web Development', 'Infrastructure', 'AI'],
      rating: 4.8,
      response_sla_hours: 32,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 2,
      name: 'GizaSystem',
      email: 'GizaSystem@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'KSA'],
      services_offered: ['Cloud Hosting', 'Mobile Development', 'AI', 'IT','Security'],
      rating: 4.1,
      response_sla_hours: 30,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 3,
      name: 'ValleySoft',
      email: 'ValleySoft@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'KSA'],
      services_offered: [
        'Web Development',
        'Cloud Hosting',
        'Integration',
        'System Design',
      ],
      rating: 4.3,
      response_sla_hours: 25,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 4,
      name: 'Smart',
      email: 'Smart@gmail.com',
      countries_supported: ['UAE', 'GER', 'KSA'],
      services_offered: [
        'Web Development',
        'Cloud Hosting',
        'Integration',
        'System Design',
      ],
      rating: 4.3,
      response_sla_hours: 28,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 5,
      name: 'Appel',
      email: 'Appel@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'USA'],
      services_offered: ['Cloud Hosting', 'Mobile Development', 'AI', 'IT'],
      rating: 4.7,
      response_sla_hours: 26,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 6,
      name: 'DELL',
      email: 'DELL@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'USA', 'GER'],
      services_offered: ['Web Development', 'AI', 'System Design', 'Security'],
      rating: 4.6,
      response_sla_hours: 24,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 7,
      name: 'Delta',
      email: 'Delta@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'KSA'],
      services_offered: [
        'Cloud Hosting',
        'Mobile Development',
        'AI',
        'System Design',
        'Data Analysis',
      ],
      rating: 4.5,
      response_sla_hours: 30,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 8,
      name: 'Sumerage',
      email: 'Sumerage@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'USA', 'ALG'],
      services_offered: [
        'Data Analysis',
        'Infrastructure',
        'Cloud Hosting',
        'Integration',
        'Web Development',
      ],
      rating: 4.4,
      response_sla_hours: 48,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 9,
      name: 'Vendor A',
      email: 'Vendor_A@gmail.com',
      countries_supported: ['UAE', 'Egypt', 'USA'],
      services_offered: [
        'Data Analysis',
        'Infrastructure',
        'Cloud Hosting',
        'Integration',
        'Web Development',
      ],
      rating: 4.3,
      response_sla_hours: 36,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'),
    },
    {
      id: 10,
      name: 'Vendor B',
      email: 'Vendor_B@gmail.com',
      countries_supported: ['UAE', 'KSA', 'USA', 'GER'],
      services_offered: [
        'Infrastructure',
        'Cloud Hosting',
        'Integration',
        'Web Development',
        'Data Analysis',
      ],
      rating: 4.2,
      response_sla_hours: 40,
      createdAt: new Date('2025-08-28T03:16:19.487109Z'),
      updatedAt: new Date('2025-08-28T03:16:19.487109Z'), 
    },
  ]);
  // Seed Projects
  await projectRepository.save([
    {
      id: 1,
      country: 'Egypt',
      title: 'Project 1',
      description: 'Project 1 description',
      services_needed: ['Cloud Hosting', 'Web Development'],
      budget: 30000,
      status: 'active',
      clientId: 1,
    },
    {
      id: 2,
      country: 'USA',
      title: 'Project 2',
      description: 'Project 2 description',
      services_needed: ['Cloud Hosting', 'Web Development'],
      budget: 28000,
      status: 'active',
      clientId: 2,
    },
    {
      id: 3,
      country: 'KSA',
      title: 'Project 3',
      description: 'Project 3 description',
      services_needed: ['AI', 'Cloud Hosting'],
      budget: 29000,
      status: 'active',
      clientId: 1,
    },
    {
      id: 4,
      country: 'GER',
      title: 'Project 4',
      description: 'Project 4 description',
      services_needed: ['Infrastructure', 'System Design'],
      budget: 18000,
      status: 'active',
      clientId: 2,
    },
    {
      id: 5,
      country: 'USA',
      title: 'Project 5',
      description: 'Project 5 description',
      services_needed: ['Web Development', 'AI'],
      budget: 32000,
      status: 'active',
      clientId: 1,
    },
    {
      id: 6,
      country: 'Egypt',
      title: 'Project 6',
      description: 'Project 6 description',
      services_needed: ['Data Analysis', 'Integration'],
      budget: 36000,
      status: 'active',
      clientId: 2,
    },
    {
      id: 7,
      country: 'USA',
      title: 'Project 7',
      description: 'Project 7 description',
      services_needed: ['Data Analysis','AI'],
      budget: 42000,
      status: 'expansion',
      clientId: 2,
    },
    {
      id: 8,
      country: 'GER',
      title: 'Project 8',
      description: 'Project 8 description',
      services_needed: ['System Design','AI'],
      budget: 34000,
      status: 'expansion',
      clientId: 2,
    },
    {
      id: 9,
      country: 'KSA',
      title: 'Project 9',
      description: 'Project 9 description',
      services_needed: ['Infrastructure','System Design'],
      budget: 56000,
      status: 'expansion',
      clientId: 1,
    },
    {
      id: 10,
      country: 'USA',
      title: 'Project 10',
      description: 'Project 10 description',
      services_needed: ['Infrastructure','Integration'],
      budget: 56000,
      status: 'expansion',
      clientId: 1,
    },
    {
      id: 11,
      country: 'KSA',
      title: 'Project 11',
      description: 'Project 11 description',
      services_needed: ['Mobile Development','Cloud Hosting'],
      budget: 62000,
      status: 'expansion',
      clientId: 2,
    },
    {
      id: 12,
      country: 'Egypt',
      title: 'Project 12',
      description: 'Project 12 description',
      services_needed: ['Web Development','AI'],
      budget: 60000,
      status: 'expansion',
      clientId: 1,
    },
    {
      id: 13,
      country: 'Egypt',
      title: 'Project 13',
      description: 'Project 13 description',
      services_needed: ['Mobile Development','Infrastructure'],
      budget: 47000,
      status: 'expansion',
      clientId: 2,
    },
  ]);
  console.log('PostgreSQL seeded successfully!');
}
